---

- hosts: all
  become: true
  pre_tasks:

  - name: update Centos 8
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "centos" and ansible_distribution_version == "8"

  - name: update Centos
    tags: always
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "centos"

  - name: update Ubuntu
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "ubuntu"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache2, php package
    tags: ubuntu, apache, apache2, php
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache2, php package
    tags: centos, apache, httpd, php
    yum:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb for ubuntu
    tags: ubuntu, db, mariadb
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install mariadb for centos
    tags: centos, db, mariadb
    yum:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package for centos 8
    tags: centos8, samba
    package:
      name: samba
      state: latest