---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (CentOS 8)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution_version =="8"

  - name: install updates (CentOS 7)
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache2, php package for ubuntu servers
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache2, php package for centos 8
    dnf:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS" and ansible_distribution_version =="8"

  - name: install apache2, php package for centos 7
    yum:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb packakge(CentOS 8)
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentoOS" and ansible_distribution_version =="8"

  - name: install mariadb packakge(CentOS 7)
    yum:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentoOS" and ansible_distribution_version =="7.9"

- hosts: was_servers
  become: true
  tasks:

  - name: install samba package
    package:
      name: samba
      state: latest
