---

- hosts: all
  become: true
  pre_tasks:

  - name: update repo chache (CentOS 7)
    tags: always
    yum:
      update_cache: yes
    changed_when: false
    when: ansible_distribution =="CentOS"

  - name: update repo chache (CentOS 8)
    tags: always
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution_version =="8"

  - name: update repo chache (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  roles:
    - base
    
- hosts: workstations
  become: true
  roles:
    - workstations

- hosts: web_servers
  become: true
  roles:
    - web_servers

- hosts: db_servers
  become: true
  roles:
    - db_servers

- hosts: file_servers
  become: true
  roles:
    - file_servers